name: app_tour_riqsiy
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_unity_widget:
    git:
      url: https://github.com/juicycleff/flutter-unity-view-widget.git
      ref: master

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  google_maps_flutter: ^2.2.0
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  font_awesome_flutter: ^10.5.0
  flutter_i18n: ^0.36.2
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_launcher_icons:
  android: true
  ios: false # Deshabilita iOS si no necesitas generar íconos para esa plataforma
  image_path: "dev_assets/logoapp1.png"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/logoapp2.png"
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/flutter_i18n/
    #imagenes de la pantalla de categorias
    - images/cat_images/atsa.jpg
    - images/cat_images/buscha.jpg
    - images/cat_images/costumbres_chachapoyas.jpg
    - images/cat_images/hotel-puma-urco.jpg
    - images/cat_images/kuelap.jpg
    - images/cat_images/paquetes_chachapoyas.jpg
    - images/cat_images/selva.jpg
    - images/cat_images/chachapoyas-calles1.jpg
    - images/cat_images/buschachapoyas.jpg
    - images/cat_images/restaurante.jpg
    - images/cat_images/productostradicionales.jpeg
    #imagenes de ciudades
    - images/ciudades/baguacity.jpg
    - images/ciudades/baguagrande.jpg
    - images/ciudades/chachapoyas.jpg
    - images/ciudades/luya.jpg
    - images/ciudades/rodriguez de mendoza.jpg
    - images/ciudades/jalca.jpeg
    - images/ciudades/molinopampa.jpg
    #imagenes de la ciudad de bagua
    - images/ciudades/bagua1.jpg
    - images/ciudades/bagua2.jpg
    - images/ciudades/bagua3.jpg
    - images/ciudades/bagua4.jpg
    - images/ciudades/bagua5.jpg
    - images/ciudades/bagua6.jpg
    - images/ciudades/bagua7.jpg
    #imagenes de la ciudad de bagua grande
    - images/ciudades/bgrande1.jpg
    - images/ciudades/bgrande2.jpg
    - images/ciudades/bgrande3.jpg
    - images/ciudades/bgrande4.jpg
    #imagenes de la ciudad de chachapoyas
    - images/ciudades/chachapoyas1.jpeg
    - images/ciudades/chachapoyas2.jpg
    - images/ciudades/chachapoyas3.jpg
    - images/ciudades/chachapoyas4.jpeg
    - images/ciudades/chachapoyas5.jpeg
    - images/ciudades/chachapoyas6.jpeg
    - images/ciudades/chachapoyas7.jpeg
    - images/ciudades/chachapoyas8.jpeg
    #imagenes de la ciudad de luya
    - images/ciudades/luya1.jpg
    - images/ciudades/luya2.jpeg
    - images/ciudades/luya3.jpeg
    - images/ciudades/luya4.jpeg
    #imagenes de la ciudad de mendoza
    - images/ciudades/mendoza1.jpg
    - images/ciudades/mendoza2.jpg
    - images/ciudades/mendoza3.jpg
    - images/ciudades/mendoza4.jpg
    - images/ciudades/mendoza5.jpg
    - images/ciudades/mendoza6.jpg
    - images/ciudades/mendoza7.jpg
    - images/ciudades/mendoza8.jpg
    - images/ciudades/mendoza9.jpg
    - images/ciudades/mendoza10.jpg
    #imagenes del carousel
    - images/carousel/agenciatravel.jpg
    - images/carousel/avionytravel.jpg
    - images/carousel/chachapoyastravel.jpg
    - images/carousel/oficetravel.jpg
    - images/carousel/travelpeople.jpg
    - images/localizacionchachapoyas.jpg
    #imagenes de centros arqueologicos
    - images/arqueologicos/kuelapar.jpeg
    - images/arqueologicos/laguan de los condores.jpeg
    - images/arqueologicos/sarcojafos de karajia.jpg
    - images/arqueologicos/wimba.jpeg
    - images/arqueologicos/quiocta.jpg
    #imagenes de kuelap
    - images/arqueologicos/keulap1.jpg
    - images/arqueologicos/kuelap2.jpg
    - images/arqueologicos/kuelap3.jpg
    - images/arqueologicos/kuelap4.jpg
    - images/arqueologicos/kuelap5.jpg
    - images/arqueologicos/kuelap6.jpg
    - images/arqueologicos/kuelap7.jpeg
    - images/arqueologicos/kuelap8.jpeg
    - images/arqueologicos/kuelap9.jpg
    - images/arqueologicos/kuelap10.jpg
    - images/arqueologicos/kuelap11.png
    #imagenes del la laguna de los condores
    - images/arqueologicos/laguna1.jpg
    - images/arqueologicos/laguna2.jpg
    - images/arqueologicos/laguna3.jpg
    #imagenes de los sarcofagos
    - images/arqueologicos/sarcofago1.jpeg
    - images/arqueologicos/sarcofago2.jpg
    - images/arqueologicos/sarcofago3.jpeg
    - images/arqueologicos/sarcofago4.jpg
    - images/arqueologicos/sarcofago5.jpg
    #imagenes de wimba
    - images/arqueologicos/wimba1.jpg
    - images/arqueologicos/wimba2.jpg
    - images/arqueologicos/wimba3.jpg
    - images/arqueologicos/wimba4.jpg
    #imagenes de la cavernad e quiocta
    - images/arqueologicos/quiocta1.jpg
    - imageS/arqueologicos/quiocta2.jpg
    - images/arqueologicos/quiocta3.jpg
    - images/arqueologicos/quiocta4.jpg
    #imagenes de aviones
    - images/aviones/atzaair.jpg
    - images/aviones/saeta.jpg
    #imagenes de avione de atza airlanes
    - images/aviones/atza1.png
    - images/aviones/atza2.png
    - images/aviones/atza3.png
    - images/aviones/atza4.png
    #imagenes de saeta
    - images/aviones/saeta1.png
    - images/aviones/saeta2.png
    - images/aviones/saeta3.png
    - images/aviones/saeta4.png
    - images/aviones/saeta5.png
    #images de buses
    - images/buses/civa.jpg
    - images/buses/ghbus.jpg
    - images/buses/movil bus.jpg
    - images/buses/chiclayo.jpg
    #imagenes de buses de civa
    - images/buses/civa1.jpeg
    - images/buses/civa2.jpeg
    - images/buses/civa3.jpeg
    - images/buses/civa4.jpg
    - images/buses/civa5.jpg
    #imagenes de buses movil
    - images/buses/movil1.jpg
    - images/buses/movil2.jpg
    - images/buses/movil3.jpg
    - images/buses/movil4.jpg
    - images/buses/movil5.jpg
    - images/buses/movil6.png
    - images/buses/movil7.png
    - images/buses/movil8.png
    #imagenes de buses gh bus
    - images/buses/gh1.jpg
    - images/buses/gh2.jpg
    - images/buses/gh3.jpg
    - images/buses/gh4.png
    #imagenes de buses transportes chiclayo
    - images/buses/chiclayo1.jpeg
    - images/buses/chiclayo2.jpg
    - images/buses/chiclayo3.jpeg
    - images/buses/chiclayo4.jpg
    #images de costumbres
    - images/costumbres/carnaval bagua grande.jpg
    - images/costumbres/fiesta de sanjuan.jpg
    - images/costumbres/raymi llacta.jpg
    - images/costumbres/yunsa.jpeg
    - images/costumbres/fiestavirgenAsunta.jpg
    - images/costumbres/aniversariochacha.jpeg
    #imagenes del carnaval
    - images/costumbres/carnaval1.jpg
    - images/costumbres/carnaval2.jpg
    - images/costumbres/carnaval3.jpg
    - images/costumbres/carnaval4.jpg
    - images/costumbres/carnaval5.jpg
    - images/costumbres/carnaval6.jpg
    - images/costumbres/carnaval7.jpg
    - images/costumbres/carnaval8.jpg
    - images/costumbres/carnaval9.jpg
    - images/costumbres/carnaval10.jpg
    #imagenes de la fiesta de san juan
    - images/costumbres/sanJuan1.jpg
    #imagenes del raymi llacta de los chachapoyas
    - images/costumbres/raymi1.jpg
    - images/costumbres/raymi2.jpg
    - images/costumbres/raymi3.jpg
    - images/costumbres/raymi4.jpg
    #imagenes de la yunsa
    - images/costumbres/yunsa1.jpg
    - images/costumbres/yunsa2.jpg
    - images/costumbres/yunsa3.jpg
    - images/costumbres/yunsa4.jpg
    - images/costumbres/yunsa5.jpg
    #imagenes de la fiesta de la virgen asunta
    - images/costumbres/asunta1.jpg
    - images/costumbres/asunta2.jpg
    - images/costumbres/asunta3.jpg
    - images/costumbres/asunto4.jpg
    - images/costumbres/asunta5.jpg
    #imagenes de hoteles
    - images/hoteles/achamaqui hotel.jpg
    - images/hoteles/gocta lodge.jpg
    - images/hoteles/pumahotel.jpg
    - images/hoteles/villa paris.jpg
    - images/hoteles/xalca hotel.jpg
    #imagenes del hotel achamaqui
    - images/hoteles/achamaqui1.jpeg
    - images/hoteles/achamaqui2.jpg
    - images/hoteles/achamaqui3.jpeg
    - images/hoteles/achamaqui4.jpg
    - images/hoteles/achamaqui5.jpeg
    - images/hoteles/achamaqui6.jpg
    - images/hoteles/achamaqui7.jpg
    - images/hoteles/achamaqui8.jpg
    - images/hoteles/achamaqui9.jpg
    - images/hoteles/achamaqui11.jpg
    - images/hoteles/achamaqui12.jpg
    - images/hoteles/achamaqui13.jpg
    - images/hoteles/achamaqui14.jpg
    - images/hoteles/achamaqui15.jpg
    - images/hoteles/achamaqui16.jpeg
    - images/hoteles/achamaqui17.jpg
    - images/hoteles/achamaqui18.jpg
    #imagenes del hotol gocta lodge
    - images/hoteles/hgocta1.jpg
    - images/hoteles/hgocta2.jpg
    - images/hoteles/hgocta3.jpg
    - images/hoteles/hgocta4.jpg
    - images/hoteles/hgocta5.jpg
    - images/hoteles/hgocta6.jpg
    - images/hoteles/hgocta7.jpg
    - images/hoteles/hgocta8.jpg
    - images/hoteles/hgocta9.jpg
    - images/hoteles/hgocta10.jpg
    - images/hoteles/hgocta11.jpg
    - images/hoteles/hgocta12.jpg
    - images/hoteles/hgocta13.jpg
    - images/hoteles/hgocta14.jpg
    - images/hoteles/hgocta15.jpg
    - images/hoteles/hgocta16.jpg
    - images/hoteles/hgocta17.jpg
    - images/hoteles/hgocta18.jpg
    #imagenes de hotel xalca
    - images/hoteles/xalca1.jpg
    - images/hoteles/xalca2.jpg
    - images/hoteles/xalca3.jpg
    - images/hoteles/xalca4.jpg
    - images/hoteles/xalca5.jpg
    - images/hoteles/xalca6.jpg
    - images/hoteles/xalca7.jpg
    - images/hoteles/xalca8.jpg
    - images/hoteles/xalca9.jpg
    - images/hoteles/xalca10.jpg
    - images/hoteles/xalca11.jpg
    - images/hoteles/xalca12.jpg
    #images del hotel puma urco
    - images/hoteles/puma1.jpg
    - images/hoteles/puma2.jpg
    - images/hoteles/puma3.jpg
    - images/hoteles/puma4.png
    - images/hoteles/puma5.png
  #images del hotel villa paris
    - images/hoteles/villa1.jpg
    - images/hoteles/villa2.jpg
    - images/hoteles/villa3.jpg
    - images/hoteles/villa4.jpg
    - images/hoteles/villa5.jpg
    - images/hoteles/villa6.jpg
    - images/hoteles/villa7.jpg
    - images/hoteles/villa8.jpg
    - images/hoteles/villa9.jpg
    - images/hoteles/villa10.jpg
    #imagenes de productos tradicionales
    - images/paquetes/chila1.jpg
    - images/paquetes/chila2.jpg
    - images/paquetes/chila3.jpg
    - images/paquetes/chila4.jpg
    - images/paquetes/chila5.jpg
    - images/paquetes/chila6.jpg
    - images/paquetes/chila7.jpg
    - images/paquetes/chila8.jpg
    - images/paquetes/chila.jpeg
    #imagenes de cafe monteverde
    - images/paquetes/cafemonteverde.jpeg
    - images/paquetes/monteverde1.png
    - images/paquetes/monteverde2.png
    - images/paquetes/monteverde3.jpeg
    - images/paquetes/monteverde4.jpeg
    - images/paquetes/monteverde5.jpg
    - images/paquetes/monteverde6.jpg
    - images/paquetes/monteverde7.jpg
    - images/paquetes/monteverde8.jpg
    - images/paquetes/monteverde9.jpg
    #imagenes de panaderia lamud
    - images/paquetes/panaderialamud.jpg
    - images/paquetes/panaderialamud1.jpg
    - images/paquetes/panaderialamud2.jpg
    - images/paquetes/panaderialamud3.jpg
    - images/paquetes/panaderialamud4.jpg
    #imagenes de los restaurantes
    - images/restaurantes/realcecina.jpg
    - images/restaurantes/misturaUrco.jpg
    - images/restaurantes/guayachos.jpg
    - images/restaurantes/batantayta.jpg
    - images/restaurantes/Amazonika.jpg
    - images/restaurantes/pollobra.jpeg
    #imagenes de la real cecina
    - images/restaurantes/realcecina1.jpg
    - images/restaurantes/realcecina2.png
    - images/restaurantes/realcecina3.png
    - images/restaurantes/realcecina4.png
    - images/restaurantes/realcecina5.png
    - images/restaurantes/realcecina6.png
    #imagenes del batan del tayta
    - images/restaurantes/batan1.jpg
    - images/restaurantes/batan2.jpg
    - images/restaurantes/batan3.jpg
    - images/restaurantes/batan4.jpg
    - images/restaurantes/batan5.jpg
    - images/restaurantes/batan6.jpg
    - images/restaurantes/batan7.jpg
    #imagenes del restaurante amazonika
    - images/restaurantes/amazonika1.jpg
    - images/restaurantes/amazonika2.jpg
    - images/restaurantes/amazonika3.jpg
    - images/restaurantes/amazonika4.jpg
    - images/restaurantes/amazonika5.jpg
    - images/restaurantes/amazonika6.jpg
    - images/restaurantes/amazonika7.jpg
    #imagenes del restaurante huayacho
    - images/restaurantes/huayacho1.jpg
    - images/restaurantes/huayacho2.jpg
    - images/restaurantes/huayacho3.jpg
    - images/restaurantes/huayacho4.jpg
    - images/restaurantes/huayacho5.jpg
    - images/restaurantes/huayacho6.jpg
    - images/restaurantes/huayacho7.jpg
    - images/restaurantes/huayacho8.jpg
    - images/restaurantes/huayacho9.jpg
    - images/restaurantes/huayacho10.jpg
    #imagenes del restaurante mistura urco
    - images/restaurantes/mistura1.jpg
    - images/restaurantes/mistura2.jpg
    - images/restaurantes/mistura3.jpg
    - images/restaurantes/mistura4.jpg
    - images/restaurantes/mistura5.jpg
    - images/restaurantes/mistura6.jpg
    - images/restaurantes/mistura7.jpg
    - images/restaurantes/mistura8.jpg
    #imagenes del restaurante hailton
    - images/restaurantes/hailton1.png
    - images/restaurantes/hailton2.png
    - images/restaurantes/hailton3.png
    - images/restaurantes/hailton4.png
    - images/restaurantes/hailton5.jpg
    #imagenes de promociones
    - images/promo/prom1.jpg
    - images/promo/prom2.jpg
    - images/promo/prom3.jpg
    - images/promo/promochachaexpedition.jpg
    - images/promo/promoexp2.jpg
    - images/promo/promoexp3.jpg
    - images/promo/promoexpresk.jpg
    - images/promo/promosuma.jpg
    #imagen home
    - images/promo/imagenhome.png
    - images/promo/home1.jpg
    - images/remame1.png
    #images del logo
    - dev_assets/logoapp1.png
    - dev_assets/logoapp2.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Black.ttf
          weight: 900

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Italic.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
 
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
